spring:
  application:
    name: ePrescriptionPoC
  datasource.driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: validate
  profiles:
    group:
      dev: default
      prod: default

app:
  fmk.endpoint.url: ${FMK_ENDPOINT_URL}
  cpr.endpoint.url: ${CPR_ENDPOINT_URL}
  sts:
    endpoint.url: http://test2.ekstern-test.nspop.dk:8080/sts/services/NewSecurityTokenService
    keystore:
      path: ${STS_KEYSTORE_PATH}
      password: ${STS_KEYSTORE_PASSWORD}
      alias: ${STS_KEYSTORE_ALIAS}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false

logging:
  level:
    root: info
    org.springframework.web: info
    dk.nsp.epps: info

---
# dev profile - running locally on developers machine (also unit tests)
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    org.springframework:
      web: info
    dk.nsp.epps: debug

---
# preprod profile
spring:
  config:
    activate:
      on-profile: preprod

logging:
  level:
    root: info
    org.springframework:
      web: info
    dk.nsp.epps: debug

---
# A profile for connecting to a database on localhost
spring:
  config:
    activate:
      on-profile: localdb

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost/epps
    username: epps
    password: epps

---
# A profile for logging the sql generated by jpa
spring:
  config:
    activate:
      on-profile: logsql

logging:
  level:
    org:
      hibernate:
        SQL: debug
