spring:
  profiles:
    active: mysql
  jpa:
    show_sql: false
tsam-sync:
  database:
    backup: false
  pageable:
    default-page-size: 250
  cts:
    url: ${CTS_URL}
    username: ${CTS_USERNAME}
    password: ${CTS_PASSWORD}
  datasource:
    host: ${MARIADB_HOST}
    port: ${MARIADB_PORT}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    database: ehealth_ltrdb
    dialect: org.hibernate.dialect.MySQL8Dialect
    driver: com.mysql.cj.jdbc.Driver
    timezone: Europe/Brussels
  datasource-ehealth-properties:
    host: ${MARIADB_HOST}
    port: ${MARIADB_PORT}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    database: ehealth_properties
    dialect: org.hibernate.dialect.MySQL8Dialect
    driver: com.mysql.cj.jdbc.Driver
    timezone: Europe/Brussels
