logging:
  level:
    com.zaxxer.hikari: warn
    eu.europa.ec.sante.ehdsi.openncp: info
    org.hibernate: warn
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    default:
      jndi-name: java:comp/env/jdbc/ConfMgr
    atna:
      jndi-name: java:comp/env/jdbc/OPEN_ATNA
    eadc:
      jndi-name: java:comp/env/jdbc/EADC
    database: default
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  jackson:
    default-property-inclusion: non_empty
  mail:
    host: 127.0.0.1
    port: 25
    username: email@ehdsi.eu
    password: password
    smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls:
        enabled: true
        required: false
      ssl:
        enable: false
        trust: "*"
server:
  error:
    include-message: always
application:
  mail:
    from: sante-ehealth-dsi-support@ec.europa.eu
  portal:
    base-url: https://openncp-gateway:8443/openncp-gateway
  security:
    jwt:
      secret: S7U418zVNeAIRmznNyNQec7eimPD0qEv
