package dk.sundhedsdatastyrelsen.ncpeh.authentication;

import lombok.Builder;
import lombok.NonNull;
import org.w3c.dom.Node;

import java.security.cert.X509Certificate;
import java.util.List;

@Builder
public record BootstrapTokenParams(
    @NonNull X509Certificate certificate,
    @NonNull String nameId,
    @NonNull String nameIdFormat,
    List<SamlAttribute> attributes,
    @NonNull String audience
) {
    public sealed interface SamlAttribute {
        /// Attribute element copied from e.g. HCP assertion
        record Raw(Node node) implements SamlAttribute {}
        /// Attribute generated by this IdP
        record New(String name, String friendlyName, List<String> values) implements SamlAttribute {}
    }
}
