networks:
  epps-backend:
    name: epps
    external: true

services:
  # Convenience tool for managing docker containers.
  # To enable: Add COMPOSE_PROFILES=portainer to .env
  portainer:
    profiles: ["portainer"]
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    container_name: portainer
    ports:
      - "${PORTAINER_PORT}:${PORTAINER_EXTERNAL_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # To manage Docker
      - portainer_data:/data # Persistent storage for Portainer
    networks:
      - ncp

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
