debug: false
spring:
  datasource:
    url: "jdbc:${DB_TYPE}://${DB_HOST}:${DB_INTERNAL_PORT}/ehealth_ltrdb?useSSL=false"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
openncp:
  root:
    path: /opt/openncp-configuration/