services:
  ehealth-portal-backend:
    container_name: ehealth-portal-backend
    env_file: .env
    build:
      context: ./ehealth-portal-backend
      dockerfile: Dockerfile
    ports:
      - "8092:8080"
      - "5443:8443"
    volumes:
      - ./logs/ehealth-portal-backend:/usr/local/tomcat/logs
      - ./ehealth-portal-backend/certificates:/opt/openncp-configuration/keystore
      - tsam-exporter-data:/opt/openncp-configuration/EpsosRepository
    networks:
      - openncp

  # # OpenNCP Frontend Portal (Node B)
  # # Portal Frontend
  ehealth-portal-frontend:
    container_name: ehealth-portal-frontend
    build:
      context: ./ehealth-portal-frontend
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      dockerfile: Dockerfile
    ports:
      - "8093:8080"
    depends_on:
      - ehealth-portal-backend
    volumes:
      - ./logs/ehealth-portal-frontend:/usr/local/tomcat/logs
    networks:
      - openncp
networks:
  openncp:
    name: openncp
    external: true
volumes:
  tsam-exporter-data:
    external: true
    name: tsam-exporter-data
