FROM tomcat:9-jdk11-temurin

# Copy the webapps
COPY target/classes/webapp/openncp-ncp-client.war /usr/local/tomcat/webapps/
COPY target/classes/lib /usr/local/tomcat/lib/

COPY ncp_officer/tomcat-config-entrypoint.sh /usr/local/tomcat/bin/
COPY ncp_officer/config /usr/local/tomcat/conf/

# needed because else we get the error:
# failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process:
# exec: "tomcat-config-entrypoint.sh": executable file not found in $PATH: unknown
RUN chmod 777 /usr/local/tomcat/bin/tomcat-config-entrypoint.sh

RUN groupadd -g 2000 tomcat && \
  useradd -r -u 2000 -g tomcat tomcat && \
  chown -R tomcat:tomcat /usr/local/tomcat/bin /usr/local/tomcat/webapps /usr/local/tomcat/conf /usr/local/tomcat/logs


# needed to be able to install additional packages
RUN apt-get update
# install the gettext package to be able to use the envsubst command used to replace environment variables
RUN apt-get -qq -y install gettext

ENTRYPOINT ["tomcat-config-entrypoint.sh"]

USER tomcat

# Start the tomcat service
CMD ["catalina.sh", "run"]
