version: '3.5'

networks:
  epps-backend:

services:

  # watchtower only runs on startup - after that it is started by the deploy pipeline on-demand
  watchtower:
    image: containrrr/watchtower
    container_name: epps-country-a-watchtower
    command: --run-once --cleanup epps-country-a epps-fmk-mock
    volumes:
      - $HOME/.docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - epps-backend

  #
  # epps-country-a service
  #
  epps-country-a:
    image: eppsregistry.azurecr.io/countrya-poc:latest
    container_name: epps-country-a
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}"
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-server/epps"
      - "SPRING_DATASOURCE_USERNAME=epps"
      - "SPRING_DATASOURCE_PASSWORD=epps"
      - "FMK_ENDPOINT_URL=${FMK_ENDPOINT_URL}"
      - "CPR_ENDPOINT_URL=${CPR_ENDPOINT_URL}"
      - "STS_KEYSTORE_PATH=${STS_KEYSTORE_PATH}"
      - "STS_KEYSTORE_ALIAS=${STS_KEYSTORE_ALIAS}"
      - "STS_KEYSTORE_PASSWORD=${STS_KEYSTORE_PASSWORD}"
    volumes:
      - "./epps-test-cert.p12:/epps-test-cert.p12:ro"
    links:
      - mariadb-server:mariadb-server
      - epps-fmk-mock:epps-fmk-mock
      # - epps-cpr-mock:epps-cpr-mock
    depends_on:
      - mariadb-server
    networks:
      - epps-backend

  #
  # fmk mock
  #
  epps-fmk-mock:
    image: eppsregistry.azurecr.io/countrya-fmk-mock:latest
    restart: always
    container_name: epps-fmk-mock
    environment:
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}"
    networks:
      - epps-backend

  #
  # cpr mock
  #
  # The CPR mock is disabled because we connect to the NSP CPR test service instead
  # epps-cpr-mock:
  #   image: eppsregistry.azurecr.io/countrya-cpr-mock:latest
  #   restart: always
  #   container_name: epps-cpr-mock
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}"
  #   networks:
  #     - epps-backend

  #
  # Database
  #
  mariadb-server:
    image: mariadb:11.1
    restart: always
    container_name: epps-country-a-db
    #ports:
    #  - "3306:3306"
    environment:
      - "MARIADB_ROOT_PASSWORD=7b1c3deda5144f99a6973f462215b8cd"
      - "MARIADB_USER=epps"
      - "MARIADB_PASSWORD=epps"
      - "MARIADB_DATABASE=epps"
    volumes:
      - type: volume
        source: countrya-data
        target: /var/lib/mysql
        read_only: false
    networks:
      - epps-backend

volumes:
  countrya-data:
    driver: local
