services:
  ehealth-portal-backend:
    container_name: ehealth-portal-backend
    env_file: countrybportal.env
    build:
      context: ./ehealth-portal-backend
      dockerfile: Dockerfile
    ports:
      - "8092:8080"
      - "5443:8443"
      - "5004:5004"
    volumes:
      - ./openncp-configuration/cert:/opt/openncp-configuration/keystore
      - tsam-exporter-data:/opt/openncp-configuration/EpsosRepository
    networks:
      - ncp
    dns:
      - 8.8.8.8
    environment:
      CATALINA_OPTS: "
        -Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5004,server=y,suspend=n"

  # # OpenNCP Frontend Portal (Node B)
  # # Portal Frontend
  ehealth-portal-frontend:
    container_name: ehealth-portal-frontend
    build:
      context: ./ehealth-portal-frontend
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      dockerfile: Dockerfile
    ports:
      - "8093:8080"
    depends_on:
      - ehealth-portal-backend
    networks:
      - ncp
networks:
  ncp:
    name: epps
    external: true
volumes:
  tsam-exporter-data:
    #external: true # Removed since it does not exist in our NCP
    name: tsam-exporter-data
