spring:
  application:
    name: NCPeH-DK-national-connector-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  profiles:
    group:
      dev: default
      prod: default

app:
  fmk.endpoint.url: ${FMK_ENDPOINT_URL}
  cpr.endpoint.url: ${CPR_ENDPOINT_URL}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false

logging:
  level:
    root: info
    org.springframework.web: info
    dk.nsp.epps: debug
