spring:
  application:
    name: NCPeH-DK-national-connector-service
  undo-datasource:
    jdbcUrl: jdbc:sqlite:data/undo-db.sqlite
  local-lms-datasource:
    jdbcUrl: jdbc:sqlite:data/local-lms-db.sqlite
  job-queue-datasource:
    jdbcUrl: jdbc:sqlite:data/job-queue.sqlite
  flyway:
    enabled: true
    locations: "classpath:db/migration"

server:
  port: 4443
  ssl:
    key-store: config/dev-keystore.jks
    key-store-password: Test.1234
    key-alias: epps-country-a
    key-password: Test.1234

# The certificate used for signing our requests to the national services.
signing-certificate-keystore:
  path: "data/epps-sosi-sts-client.jks"
  alias: "epps-sosi-sts-client"
  password: ${SOSI_KEYSTORE_PASSWORD:}

app:
  fmk.endpoint.url: https://test2.fmk.netic.dk/idws_xua/fmk_xua_146_E6
  sosi:
    endpoint.url: "https://test2-cnsp.ekstern-test.nspop.dk:8443/sts/services/DKNCPBST2EHDSIIdws"
    issuer: "https://ehdsi-idp.testkald.nspop.dk"
  sosi-system-dgws.endpoint.url: "http://test2.ekstern-test.nspop.dk:8080/sts/services/NewSecurityTokenService"
  cpr.endpoint.url: "https://test2.ekstern-test.nspop.dk:8443/stamdata-cpr-ws/service/DetGodeCPROpslag-1.0.4"
  minlog.endpoint.url: "https://test2-cnsp.ekstern-test.nspop.dk:8443/decoupling"
  authorization-registry.endpoint.url: https://test1.ekstern-test.nspop.dk:8443/stamdata-authorization-lookup-ws/service/AuthorizationCodeService-20240105
  fsk.endpoint.url: https://test1-cnsp.ekstern-test.nspop.dk:8443/decoupling
  minlog:
    max-attempts: 3

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  health:
    diskspace:
      enabled: false

logging:
  # https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md#spring-boot
  pattern.level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p"
  level:
    root: info
    org.springframework.web: info
    dk.sundhedsdatastyrelsen.ncpeh: info

lmsftp:
  server: "ftp.medicinpriser.dk"
  port: 21
  username: ${LMSFTP_USERNAME:}
  password: ${LMSFTP_PASSWORD:}
