spring:
  application:
    name: NCPeH-DK-national-connector-service
  undo-datasource:
    jdbcUrl: jdbc:sqlite:data/undo-db.sqlite
    driver-class-name: org.sqlite.JDBC
  lms-datasource:
    jdbcUrl: jdbc:sqlite:data/lms-db.sqlite
    driver-class-name: org.sqlite.JDBC
  flyway:
    enabled: true
    locations: "classpath:db/migration"

app:
  fmk.endpoint.url: "https://test2-cnsp.ekstern-test.nspop.dk:8443/decoupling"
  cpr.endpoint.url: "https://test2.ekstern-test.nspop.dk:8443/stamdata-cpr-ws/service/DetGodeCPROpslag-1.0.4"
  authorization-registry.endpoint.url: "https://test2.ekstern-test.nspop.dk:8443/stamdata-authorization-lookup-ws/service/AuthorizationCodeService"

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false

logging:
  level:
    root: info
    org.springframework.web: info
    dk.sundhedsdatastyrelsen.ncpeh: info
lmsftp:
  server: "ftp.medicinpriser.dk"
  port: 21
  username: ${LMSFTP_USERNAME}
  password: ${LMSFTP_PASSWORD}
