global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'country-a-service'
    static_configs:
      - targets: ['epps-country-a:9464']

  - job_name: 'openncp-server'
    static_configs:
      - targets: ['openncp-server:9464']

  - job_name: 'openncp-client'
    static_configs:
      - targets: ['openncp-client:9464']

  - job_name: 'openncp-openatna'
    static_configs:
      - targets: ['openncp-openatna:9464']

  - job_name: 'openncp-trc-sts'
    static_configs:
      - targets: ['openncp-trc-sts:9464']

  - job_name: 'openncp-translations-and-mappings'
    static_configs:
      - targets: ['openncp-translations-and-mappings:9464']

  - job_name: 'openncp-web-manager'
    static_configs:
      - targets: ['openncp-web-manager:9464']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
