# See: https://tomcat.apache.org/tomcat-7.0-doc/RUNNING.txt#:~:text=(3.4)

DB_PWD=$(cat "${DB_PWD_FILE}")
DB_USER=$(cat "${DB_USER_FILE}")
KEYSTORE_PASSWORD=$(cat "${KEYSTORE_PASSWORD_FILE}")
TRUSTSTORE_PASSWORD=$(cat "${TRUSTSTORE_PASSWORD_FILE}")


# export CATALINA_HOME=/usr/local/tomcat
# export CATALINA_BASE=/usr/local/tomcat

# MARIADB_USERNAME="$(cat "${MARIADB_USERNAME_FILE}")"
# MARIADB_PASSWORD="$(cat "${MARIADB_PASSWORD_FILE}")"
# TLS_KEYSTORE_PASSWORD="$(cat "${TLS_KEYSTORE_PASSWORD_FILE}")"
# TLS_TRUSTSTORE_PASSWORD="$(cat "${TLS_TRUSTSTORE_PASSWORD_FILE}")"

# # Used in server.xml:
# CATALINA_OPTS="$CATALINA_OPTS -Ddb.host=\"${DB_HOST}\""
# CATALINA_OPTS="$CATALINA_OPTS -Ddb.port=\"${DB_PORT}\""
# CATALINA_OPTS="$CATALINA_OPTS -Ddb.username=\"${MARIADB_USERNAME}\""
# CATALINA_OPTS="$CATALINA_OPTS -Ddb.password=\"${MARIADB_PASSWORD}\""
# CATALINA_OPTS="$CATALINA_OPTS -Dtls.keystore.alias=\"${TLS_KEYSTORE_ALIAS}\""
# CATALINA_OPTS="$CATALINA_OPTS -Dtls.keystore.file=\"${TLS_KEYSTORE_FILE}\""
# CATALINA_OPTS="$CATALINA_OPTS -Dtls.keystore.password=\"${TLS_KEYSTORE_PASSWORD}\""
# CATALINA_OPTS="$CATALINA_OPTS -Dtls.truststore.file=\"${TLS_TRUSTSTORE_FILE}\""
# CATALINA_OPTS="$CATALINA_OPTS -Dtls.truststore.password=\"${TLS_TRUSTSTORE_PASSWORD}\""
