global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'country-a-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['epps-country-a:8080']
