spring:
  application:
    name: ePrescriptionPoC-fmk-mock

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false

logging:
  level:
    root: info
    org.springframework: info
    org.springframework.ws:
      client.MessageTracing:
        sent: debug
        received: trace
      server.MessageTracing:
        sent: debug
        received: trace
    dk.nsp.epps: debug
