logging:
  level:
    org.apache.axis2: info
    com.zaxxer.hikari: warn
    eu.europa.ec.sante.openncp: info
    org.hibernate: warn
spring:
  jackson:
    default-property-inclusion: non_empty
  datasource:
    jndi:
      tsam:
        jndiName: java:comp/env/jdbc/TSAM
      properties:
        jndiName: java:comp/env/jdbc/ConfMgr
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

hapi:
  fhir:
    validation:
      enabled: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
