debug: false
logging:
  level:
     org.hibernate: ERROR
     org.springframework.web.client: DEBUG
     eu.epsos: DEBUG
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    hibernate:
      naming:
        physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  datasource:
    url: "jdbc:${DB_TYPE}://${DB_HOST}:${DB_INTERNAL_PORT}/ehealth_properties?allowPublicKeyRetrieval=true&useSSL=false"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
openncp:
  property-file:
    path: openncp-configuration.properties
profiles:
   active: mysql
