FROM tomcat:9-jdk11-temurin

ENV EPSOS_PROPS_PATH=/opt/openncp-configuration/

COPY target/classes/webapp/openncp-gateway-backend.war /usr/local/tomcat/webapps/
COPY target/classes/lib /usr/local/tomcat/lib/

COPY openncp-web-manager/openncp-web-manager-backend/tomcat-config-entrypoint.sh /usr/local/tomcat/bin/
COPY openncp-web-manager/openncp-web-manager-backend/config /usr/local/tomcat/conf/
COPY openncp-web-manager/openncp-web-manager-backend/application-docker.yml /opt/config/

COPY openncp-configuration/ $EPSOS_PROPS_PATH

# needed because else we get the error:
# failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process:
# exec: "tomcat-config-entrypoint.sh": executable file not found in $PATH: unknown
RUN chmod 777 /usr/local/tomcat/bin/tomcat-config-entrypoint.sh

RUN groupadd -g 2000 tomcat && \
  useradd -r -u 2000 -g tomcat tomcat && \
  chown -R tomcat:tomcat /usr/local/tomcat/bin /usr/local/tomcat/webapps /usr/local/tomcat/conf /usr/local/tomcat/logs $EPSOS_PROPS_PATH

RUN apt-get update && apt-get -qq -y install gettext socat

ENTRYPOINT ["tomcat-config-entrypoint.sh"]

USER tomcat

# Start the tomcat service
CMD ["catalina.sh", "run"]
