name: Build NCP Docker Images

on:
  push:
    branches: [ "main", "cfb/docker-8", "hbg/wave-8-nc"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set default env vars for Docker Compose
      run: cp NCP/env_default/.env NCP/.env

    - name: Build images
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: cd NCP && docker compose build --quiet

    - name: Push images
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: cd NCP && docker compose push

    - name: Log out from Docker Hub
      run: docker logout
