# The name is used to link workflows. Don't change it.
name: NCP Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'NCP/**'
    tags:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  AZURE_REGISTRY: eppsregistry.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ env.AZURE_REGISTRY }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    # The "docker compose build" command fail due to unresolved environment
    # variables unless we provide a ".env" file with some values, even though we
    # only need the environment variables at runtime and not for building.
    - name: Set default env vars for Docker Compose
      run: cp NCP/env_default/.env NCP/.env

    - name: Build and push images (single build)
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: cd NCP && docker buildx bake --file docker-compose.yml --file docker-compose-cache.json --push

    - name: Mirror tags to GHCR and ACR
      run: |
        images=(
          "dk-ncp-tsam-exporter"
          "dk-ncp-tsam-synchronizer"
          "dk-ncp-node-a"
          "dk-ncp-node-b"
          "dk-ncp-openatna"
          "dk-ncp-trc-sts"
          "dk-ncp-translations-and-mappings"
          "dk-ncp-web-manager-backend"
          "dk-ncp-configuration-utility"
        )
        for image in "${images[@]}"; do
          src="ghcr.io/sundhedsdatastyrelsen/ehdsi/${image}:${{ github.sha }}"
          # Mirror sha -> GHCR latest
          docker buildx imagetools create \
            --tag "ghcr.io/sundhedsdatastyrelsen/ehdsi/${image}:latest" \
            "$src"
          # Mirror sha -> ACR sha, latest, build-run-number
          docker buildx imagetools create \
            --tag "${{ env.AZURE_REGISTRY }}/sundhedsdatastyrelsen/ehdsi/${image}:${{ github.sha }}" \
            --tag "${{ env.AZURE_REGISTRY }}/sundhedsdatastyrelsen/ehdsi/${image}:latest" \
            --tag "${{ env.AZURE_REGISTRY }}/sundhedsdatastyrelsen/ehdsi/${image}:build-${{ github.run_number }}" \
            "$src"
        done
