name: Build NCP Docker Images

on:
  push:
    branches: [ "main", "cfb/docker-8-ncp-build-and-push"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push images
      run: |
        # Define the image name and registry
        IMAGE_NAME=ghcr.io/sundhedsdatastyrelsen/ehdsi/dk-ncp

        # Build and push for each target
        docker build --target node-a -t $IMAGE_NAME-node-a:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-node-a:${{ github.sha }}

        docker build --target node-b -t $IMAGE_NAME-node-b:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-node-b:${{ github.sha }}

        docker build --target trc-sts -t $IMAGE_NAME-trc-sts:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-trc-sts:${{ github.sha }}

        docker build --target openatna -t $IMAGE_NAME-openatna:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-openatna:${{ github.sha }}

        docker build --target openatna -t $IMAGE_NAME-web-manager-backend:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-web-manager-backend:${{ github.sha }}

        docker build --target openatna -t $IMAGE_NAME-translations-and-mappings:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-translations-and-mappings:${{ github.sha }}

        docker build --target openatna -t $IMAGE_NAME-tsam-sync:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-tsam-sync:${{ github.sha }}

        docker build --target openatna -t $IMAGE_NAME-configuration-utility:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-configuration-utility:${{ github.sha }}

        docker build --target openatna -t $IMAGE_NAME-web-manager-frontend:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-web-manager-frontend:${{ github.sha }}

        docker build --target openatna -t $IMAGE_NAME-tsam-exporter:${{ github.sha }} ./NCP
        docker push $IMAGE_NAME-tsam-exporter:${{ github.sha }}

    - name: Log out from Docker Hub
      run: docker logout