name: Deploy NCP with Docker Compose

on:
  workflow_run:
    workflows: ["Build NCP Docker Images"]  
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_VM_USER }}@${{ secrets.DEV_VM_HOST }} << 'EOF'
            # 1. Clone or pull the latest changes from your repository
            if [ -d "/var/ehdsi" ]; then
              cd /var/ehdsi && git pull
            else
              git clone https://github.com/Sundhedsdatastyrelsen/ehdsi.git /var/ehdsi
            fi

            cd /var/ehdsi/NCP

            # 2. Log in to GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 3. Pull the Docker images (if any are specified in the docker-compose.yml)
            sudo IMAGE_TAG=${{ github.sha }} docker compose pull 

            # 4. Deploy the services
            sudo IMAGE_TAG=${{ github.sha }} docker compose up -d 
          EOF
