name: Nightly integration test

on:
  workflow_dispatch:
  push: # temporary
    branches: [ "hbg/nightly-gh-action" ]
  schedule:
    - cron: "30 01 * * *"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: maven
    # - name: Build with Maven
    #   run: cd country-a-service && mvn --batch-mode --projects testing-tools --also-make package
    # - name: Create new prescriptions in FMK
    #   run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.CreateNewPrescriptionUtil
    # - name: Get the prescriptions from FMK
    #   run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GetPrescriptionsFromFmkUtil
    # - name: Generate CDA Documentation
    #   run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GenerateCdaDocumentUtil
    - name: Temp
      run: |
        mkdir -p testing-shared/src/main/resources/test-file-storage
        touch testing-shared/src/main/resources/test-file-storage/temp
    - name: Upload test files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-files
        path: testing-shared/src/main/resources/test-file-storage
    #Insert country-b part here

  edispensation-generation:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Download test files
        uses: actions/download-artifact@v4
        with:
          name: test-files
          path: input-files
      - name: Set up Docker
        run: sudo service docker start

      - name: Generate eDispensation CDA
        run: |
          docker pull ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli
          docker run ghcr.io/sundhedsdatastyrelsen/ehealth-portal-edispensation-generator:generate-edispensation-cli > input-files/edispensation-cda.xml

      - name: Upload eDispensation CDAs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: input-files
