name: Nightly integration test

on:
  workflow_dispatch:
  push:
    branches: [ "hbg/nightly-gh-action" ]
  schedule:
    - cron: "30 01 * * *"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: maven
    - name: Build with Maven
      run: cd country-a-service && mvn --batch-mode --projects testing-tools --also-make package
    - name: Create new prescriptions in FMK
      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.CreateNewPrescriptionUtil
    - name: Get the prescriptions from FMK
      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GetPrescriptionsFromFmkUtil
    - name: Generate CDA Documentation
      run: java -cp country-a-service/testing-tools/target/testing-tools-1.0.0-SNAPSHOT-shaded.jar dk.nsp.epps.script.GenerateCdaDocumentUtil
    #Insert country-b part here
