USE `ehealth_properties`;

-- pwd is set as Password1!
INSERT INTO EHNCP_USER (ID,USERNAME,PASSWORD,ENABLED,VERIFICATION_CODE,EMAIL,RESET_DATE,RESET_KEY) VALUES (1,'admin','$2a$12$UiFNjYtrGt42z1Xpisn9..okSMJuFznWgORMpfBHgliINGFS46pvq',1,NULL,'admin@email.com',NULL,NULL);

INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,2);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,3);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,4);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,5);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,6);